// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddRegionArgs {
    pub region_id: i64,
    pub region_name: String,
    pub description: String,
}

impl From<AddRegionArgs> for super::Reducer {
    fn from(args: AddRegionArgs) -> Self {
        Self::AddRegion {
            region_id: args.region_id,
            region_name: args.region_name,
            description: args.description,
        }
    }
}

impl __sdk::InModule for AddRegionArgs {
    type Module = super::RemoteModule;
}

pub struct AddRegionCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_region`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_region {
    /// Request that the remote module invoke the reducer `add_region` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_region`] callbacks.
    fn add_region(
        &self,
        region_id: i64,
        region_name: String,
        description: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_region`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddRegionCallbackId`] can be passed to [`Self::remove_on_add_region`]
    /// to cancel the callback.
    fn on_add_region(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i64, &String, &String) + Send + 'static,
    ) -> AddRegionCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_region`],
    /// causing it not to run in the future.
    fn remove_on_add_region(&self, callback: AddRegionCallbackId);
}

impl add_region for super::RemoteReducers {
    fn add_region(
        &self,
        region_id: i64,
        region_name: String,
        description: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "add_region",
            AddRegionArgs {
                region_id,
                region_name,
                description,
            },
        )
    }
    fn on_add_region(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i64, &String, &String) + Send + 'static,
    ) -> AddRegionCallbackId {
        AddRegionCallbackId(self.imp.on_reducer(
            "add_region",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AddRegion {
                                    region_id,
                                    region_name,
                                    description,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, region_id, region_name, description)
            }),
        ))
    }
    fn remove_on_add_region(&self, callback: AddRegionCallbackId) {
        self.imp.remove_on_reducer("add_region", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_region`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_region {
    /// Set the call-reducer flags for the reducer `add_region` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_region(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_region for super::SetReducerFlags {
    fn add_region(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_region", flags);
    }
}
