// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::constellation_type::Constellation;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddConstellationArgs {
    pub constellation: Constellation,
}

impl From<AddConstellationArgs> for super::Reducer {
    fn from(args: AddConstellationArgs) -> Self {
        Self::AddConstellation {
            constellation: args.constellation,
        }
    }
}

impl __sdk::InModule for AddConstellationArgs {
    type Module = super::RemoteModule;
}

pub struct AddConstellationCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_constellation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_constellation {
    /// Request that the remote module invoke the reducer `add_constellation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_constellation`] callbacks.
    fn add_constellation(&self, constellation: Constellation) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_constellation`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddConstellationCallbackId`] can be passed to [`Self::remove_on_add_constellation`]
    /// to cancel the callback.
    fn on_add_constellation(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Constellation) + Send + 'static,
    ) -> AddConstellationCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_constellation`],
    /// causing it not to run in the future.
    fn remove_on_add_constellation(&self, callback: AddConstellationCallbackId);
}

impl add_constellation for super::RemoteReducers {
    fn add_constellation(&self, constellation: Constellation) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_constellation", AddConstellationArgs { constellation })
    }
    fn on_add_constellation(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Constellation) + Send + 'static,
    ) -> AddConstellationCallbackId {
        AddConstellationCallbackId(self.imp.on_reducer(
            "add_constellation",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddConstellation { constellation },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, constellation)
            }),
        ))
    }
    fn remove_on_add_constellation(&self, callback: AddConstellationCallbackId) {
        self.imp.remove_on_reducer("add_constellation", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_constellation`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_constellation {
    /// Set the call-reducer flags for the reducer `add_constellation` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_constellation(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_constellation for super::SetReducerFlags {
    fn add_constellation(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_constellation", flags);
    }
}
