// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use super::constellation_type::Constellation;
use super::db_vector_3_f_64_type::DbVector3F64;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `constellations`.
///
/// Obtain a handle from the [`ConstellationsTableAccess::constellations`] method on [`super::RemoteTables`],
/// like `ctx.db.constellations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.constellations().on_insert(...)`.
pub struct ConstellationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Constellation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `constellations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConstellationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConstellationsTableHandle`], which mediates access to the table `constellations`.
    fn constellations(&self) -> ConstellationsTableHandle<'_>;
}

impl ConstellationsTableAccess for super::RemoteTables {
    fn constellations(&self) -> ConstellationsTableHandle<'_> {
        ConstellationsTableHandle {
            imp: self.imp.get_table::<Constellation>("constellations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConstellationsInsertCallbackId(__sdk::CallbackId);
pub struct ConstellationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConstellationsTableHandle<'ctx> {
    type Row = Constellation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Constellation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConstellationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConstellationsInsertCallbackId {
        ConstellationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConstellationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConstellationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConstellationsDeleteCallbackId {
        ConstellationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConstellationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Constellation>("constellations");
    _table.add_unique_constraint::<i64>("constellation_id", |row| &row.constellation_id);
}
pub struct ConstellationsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConstellationsTableHandle<'ctx> {
    type UpdateCallbackId = ConstellationsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConstellationsUpdateCallbackId {
        ConstellationsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConstellationsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Constellation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Constellation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `constellation_id` unique index on the table `constellations`,
/// which allows point queries on the field of the same name
/// via the [`ConstellationsConstellationIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.constellations().constellation_id().find(...)`.
pub struct ConstellationsConstellationIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Constellation, i64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConstellationsTableHandle<'ctx> {
    /// Get a handle on the `constellation_id` unique index on the table `constellations`.
    pub fn constellation_id(&self) -> ConstellationsConstellationIdUnique<'ctx> {
        ConstellationsConstellationIdUnique {
            imp: self.imp.get_unique_constraint::<i64>("constellation_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConstellationsConstellationIdUnique<'ctx> {
    /// Find the subscribed row whose `constellation_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i64) -> Option<Constellation> {
        self.imp.find(col_val)
    }
}
