// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit e107144998a2ca83ae87f905ff8a6eb5a50ff504).

#![allow(unused, clippy::all)]
use super::cse_server_version_type::CseServerVersion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `version`.
///
/// Obtain a handle from the [`VersionTableAccess::version`] method on [`super::RemoteTables`],
/// like `ctx.db.version()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.version().on_insert(...)`.
pub struct VersionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CseServerVersion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `version`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VersionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VersionTableHandle`], which mediates access to the table `version`.
    fn version(&self) -> VersionTableHandle<'_>;
}

impl VersionTableAccess for super::RemoteTables {
    fn version(&self) -> VersionTableHandle<'_> {
        VersionTableHandle {
            imp: self.imp.get_table::<CseServerVersion>("version"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VersionInsertCallbackId(__sdk::CallbackId);
pub struct VersionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VersionTableHandle<'ctx> {
    type Row = CseServerVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CseServerVersion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VersionInsertCallbackId {
        VersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VersionDeleteCallbackId {
        VersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CseServerVersion>("version");
    _table.add_unique_constraint::<String>("version_name", |row| &row.version_name);
}
pub struct VersionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VersionTableHandle<'ctx> {
    type UpdateCallbackId = VersionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VersionUpdateCallbackId {
        VersionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VersionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CseServerVersion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CseServerVersion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `version_name` unique index on the table `version`,
/// which allows point queries on the field of the same name
/// via the [`VersionVersionNameUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.version().version_name().find(...)`.
pub struct VersionVersionNameUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CseServerVersion, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VersionTableHandle<'ctx> {
    /// Get a handle on the `version_name` unique index on the table `version`.
    pub fn version_name(&self) -> VersionVersionNameUnique<'ctx> {
        VersionVersionNameUnique {
            imp: self.imp.get_unique_constraint::<String>("version_name"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VersionVersionNameUnique<'ctx> {
    /// Find the subscribed row whose `version_name` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<CseServerVersion> {
        self.imp.find(col_val)
    }
}
